deployment:
tasks:
- export DEPLOY_PATH=/home/tritec/repositories/smartVal
- export COMPOSER_BIN=/usr/local/bin/composer
pre_deploy:
- echo "Starting pre-deploy tasks..."
deploy:
- echo "Pulling latest code..."
- cd $DEPLOY_PATH
- git reset --hard origin/main
- git clean -fd
- echo "Installing Composer dependencies..."
- $COMPOSER_BIN install --no-dev --optimize-autoloader
- echo "Running Artisan commands..."
- php artisan config:cache
- php artisan route:cache
- php artisan view:cache
- php artisan migrate --force
post_deploy:
- echo "Deployment complete!"
